"""phase2 foundation

Revision ID: cac143cd9235
Revises: 
Create Date: 2026-09-15 12:28:34.486064
"""
from alembic import op
import sqlalchemy as sa
from app.infra.rls import enable_rls_sql, disable_rls_sql, app_role_sql
from app.infra.settings import get_settings
from app.models.base import TENANT_TABLES
import app.models  # noqa: F401
from sqlalchemy.dialects import postgresql

revision = 'cac143cd9235'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_type',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('vertical', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('name_et', sa.String(length=100), nullable=False),
    sa.Column('schema_ref', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('contract_type',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('vertical', sa.String(length=40), nullable=True),
    sa.Column('name_et', sa.String(length=100), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=True),
    sa.Column('locale', sa.String(length=8), server_default='et', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('attachment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_type', sa.String(length=40), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('s3_key', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachment_account_id'), 'attachment', ['account_id'], unique=False)
    op.create_index(op.f('ix_attachment_subject_id'), 'attachment', ['subject_id'], unique=False)
    op.create_index(op.f('ix_attachment_subject_type'), 'attachment', ['subject_type'], unique=False)
    op.create_table('auth_session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_session_user_id'), 'auth_session', ['user_id'], unique=False)
    op.create_table('company',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('registry_code', sa.String(length=40), nullable=True),
    sa.Column('vat_number', sa.String(length=40), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=60), nullable=True),
    sa.Column('accent_color', sa.String(length=16), nullable=True),
    sa.Column('logo_attachment_id', sa.UUID(), nullable=True),
    sa.Column('registry_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_account_id'), 'company', ['account_id'], unique=False)
    op.create_table('domain_event',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('actor_type', sa.String(length=10), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('on_behalf_of', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_event_account_id'), 'domain_event', ['account_id'], unique=False)
    op.create_index(op.f('ix_domain_event_correlation_id'), 'domain_event', ['correlation_id'], unique=False)
    op.create_index('ix_domain_event_entity', 'domain_event', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_domain_event_ts'), 'domain_event', ['ts'], unique=False)
    op.create_table('key_date_kind',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name_et', sa.String(length=100), nullable=False),
    sa.Column('vertical', sa.String(length=40), nullable=True),
    sa.Column('default_notify_days', sa.Integer(), server_default='30', nullable=False),
    sa.Column('notify_client', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kdkind_code', 'key_date_kind', ['code'], unique=False)
    op.create_table('membership',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('invited_email', sa.String(length=320), nullable=True),
    sa.Column('invite_token', sa.String(length=120), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notification_prefs', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('delegate_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['delegate_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'user_id', name='uq_membership'),
    sa.UniqueConstraint('invite_token')
    )
    op.create_index(op.f('ix_membership_account_id'), 'membership', ['account_id'], unique=False)
    op.create_index(op.f('ix_membership_user_id'), 'membership', ['user_id'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('recipient_email', sa.String(length=320), nullable=True),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('subject_type', sa.String(length=40), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_status', sa.String(length=20), server_default='none', nullable=False),
    sa.Column('email_message_id', sa.String(length=120), nullable=True),
    sa.Column('email_error', sa.Text(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_account_id'), 'notification', ['account_id'], unique=False)
    op.create_index(op.f('ix_notification_email_message_id'), 'notification', ['email_message_id'], unique=False)
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_table('party',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('registry_code', sa.String(length=40), nullable=True),
    sa.Column('personal_code', sa.String(length=40), nullable=True),
    sa.Column('vat_number', sa.String(length=40), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=60), nullable=True),
    sa.Column('roles', postgresql.ARRAY(sa.String(length=30)), server_default='{}', nullable=False),
    sa.Column('registry_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_party_account_id'), 'party', ['account_id'], unique=False)
    op.create_index(op.f('ix_party_registry_code'), 'party', ['registry_code'], unique=False)
    op.create_table('search_index',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('subtitle', sa.String(length=400), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('tsv', postgresql.TSVECTOR(), nullable=True),
    sa.Column('link', sa.String(length=300), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', name='uq_search_entity')
    )
    op.create_index(op.f('ix_search_index_account_id'), 'search_index', ['account_id'], unique=False)
    op.create_index('ix_search_tsv', 'search_index', ['tsv'], unique=False, postgresql_using='gin')
    op.create_table('asset',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_type_id', sa.UUID(), nullable=False),
    sa.Column('type_code', sa.String(length=40), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('capacity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_type.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_account_id'), 'asset', ['account_id'], unique=False)
    op.create_index(op.f('ix_asset_asset_type_id'), 'asset', ['asset_type_id'], unique=False)
    op.create_index(op.f('ix_asset_company_id'), 'asset', ['company_id'], unique=False)
    op.create_index(op.f('ix_asset_parent_id'), 'asset', ['parent_id'], unique=False)
    op.create_index(op.f('ix_asset_type_code'), 'asset', ['type_code'], unique=False)
    op.create_table('contract',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('contract_type_id', sa.UUID(), nullable=False),
    sa.Column('type_code', sa.String(length=40), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('party_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('origin', sa.String(length=10), nullable=False),
    sa.Column('has_clause_tree', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('signed_at', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('current_values', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['contract_type_id'], ['contract_type.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['party.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_account_id'), 'contract', ['account_id'], unique=False)
    op.create_index('ix_contract_account_status', 'contract', ['account_id', 'status'], unique=False)
    op.create_index(op.f('ix_contract_company_id'), 'contract', ['company_id'], unique=False)
    op.create_index(op.f('ix_contract_number'), 'contract', ['number'], unique=False)
    op.create_index(op.f('ix_contract_party_id'), 'contract', ['party_id'], unique=False)
    op.create_index(op.f('ix_contract_status'), 'contract', ['status'], unique=False)
    op.create_index(op.f('ix_contract_type_code'), 'contract', ['type_code'], unique=False)
    op.create_table('key_date',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_type', sa.String(length=20), server_default='contract', nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('kind_id', sa.UUID(), nullable=False),
    sa.Column('kind_code', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('notify_days_before', sa.Integer(), server_default='30', nullable=False),
    sa.Column('fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['kind_id'], ['key_date_kind.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_key_date_account_id'), 'key_date', ['account_id'], unique=False)
    op.create_index('ix_key_date_due', 'key_date', ['account_id', 'due_date'], unique=False)
    op.create_index(op.f('ix_key_date_kind_code'), 'key_date', ['kind_code'], unique=False)
    op.create_index(op.f('ix_key_date_subject_id'), 'key_date', ['subject_id'], unique=False)
    op.create_table('template',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('contract_type_code', sa.String(length=40), server_default='lease', nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('supersedes_id', sa.UUID(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('source_attachment_id', sa.UUID(), nullable=True),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('node_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_account_id'), 'template', ['account_id'], unique=False)
    op.create_table('allocation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('area_m2', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocation_account_id'), 'allocation', ['account_id'], unique=False)
    op.create_index(op.f('ix_allocation_asset_id'), 'allocation', ['asset_id'], unique=False)
    op.create_index('ix_allocation_asset_period', 'allocation', ['asset_id', 'period_start', 'period_end'], unique=False)
    op.create_index(op.f('ix_allocation_contract_id'), 'allocation', ['contract_id'], unique=False)
    op.create_table('clause',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('container', sa.String(length=20), server_default='body', nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('number_style', sa.String(length=12), server_default='decimal', nullable=False),
    sa.Column('category', sa.String(length=12), server_default='general', nullable=False),
    sa.Column('heading', sa.String(length=300), nullable=True),
    sa.Column('text', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('locked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('source', sa.String(length=12), server_default='template', nullable=False),
    sa.Column('source_number', sa.String(length=30), nullable=True),
    sa.Column('source_template_id', sa.UUID(), nullable=True),
    sa.Column('overrides_clause_id', sa.UUID(), nullable=True),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ),
    sa.ForeignKeyConstraint(['overrides_clause_id'], ['clause.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_id'], ['clause.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clause_account_id'), 'clause', ['account_id'], unique=False)
    op.create_index(op.f('ix_clause_contract_id'), 'clause', ['contract_id'], unique=False)
    op.create_index('ix_clause_contract_parent', 'clause', ['contract_id', 'parent_id', 'ordinal'], unique=False)
    op.create_index(op.f('ix_clause_template_id'), 'clause', ['template_id'], unique=False)
    op.create_table('contract_fact',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reason', sa.String(length=20), nullable=False),
    sa.Column('superseded_by', sa.UUID(), nullable=True),
    sa.Column('source_clause_id', sa.UUID(), nullable=True),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_fact_account_id'), 'contract_fact', ['account_id'], unique=False)
    op.create_index(op.f('ix_contract_fact_contract_id'), 'contract_fact', ['contract_id'], unique=False)
    op.create_index('ix_fact_contract_key', 'contract_fact', ['contract_id', 'key'], unique=False)
    op.create_table('source_document',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('s3_key', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('has_text_layer', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('container_signatures', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('datafiles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extracted_text_s3_key', sa.String(length=500), nullable=True),
    sa.Column('role', sa.String(length=20), server_default='original', nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_document_account_id'), 'source_document', ['account_id'], unique=False)
    op.create_index(op.f('ix_source_document_contract_id'), 'source_document', ['contract_id'], unique=False)
    op.create_index(op.f('ix_source_document_sha256'), 'source_document', ['sha256'], unique=False)
    op.create_table('import_job',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('proposal', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reviewed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prompt_version', sa.String(length=40), nullable=True),
    sa.Column('model', sa.String(length=60), nullable=True),
    sa.Column('usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duplicate_of_contract_id', sa.UUID(), nullable=True),
    sa.Column('committed_contract_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('edits_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_job_account_id'), 'import_job', ['account_id'], unique=False)
    op.create_index(op.f('ix_import_job_source_document_id'), 'import_job', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_import_job_status'), 'import_job', ['status'], unique=False)
    # ### end Alembic commands ###
    # --- tenancy: RLS on every tenant table (architecture §8) ---
    for t in TENANT_TABLES:
        for stmt in enable_rls_sql(t):
            op.execute(stmt)
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    if get_settings().db_app_role:
        for stmt in app_role_sql(get_settings().db_app_role):
            op.execute(stmt)


def downgrade() -> None:
    for t in TENANT_TABLES:
        for stmt in disable_rls_sql(t):
            op.execute(stmt)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_job_status'), table_name='import_job')
    op.drop_index(op.f('ix_import_job_source_document_id'), table_name='import_job')
    op.drop_index(op.f('ix_import_job_account_id'), table_name='import_job')
    op.drop_table('import_job')
    op.drop_index(op.f('ix_source_document_sha256'), table_name='source_document')
    op.drop_index(op.f('ix_source_document_contract_id'), table_name='source_document')
    op.drop_index(op.f('ix_source_document_account_id'), table_name='source_document')
    op.drop_table('source_document')
    op.drop_index('ix_fact_contract_key', table_name='contract_fact')
    op.drop_index(op.f('ix_contract_fact_contract_id'), table_name='contract_fact')
    op.drop_index(op.f('ix_contract_fact_account_id'), table_name='contract_fact')
    op.drop_table('contract_fact')
    op.drop_index(op.f('ix_clause_template_id'), table_name='clause')
    op.drop_index('ix_clause_contract_parent', table_name='clause')
    op.drop_index(op.f('ix_clause_contract_id'), table_name='clause')
    op.drop_index(op.f('ix_clause_account_id'), table_name='clause')
    op.drop_table('clause')
    op.drop_index(op.f('ix_allocation_contract_id'), table_name='allocation')
    op.drop_index('ix_allocation_asset_period', table_name='allocation')
    op.drop_index(op.f('ix_allocation_asset_id'), table_name='allocation')
    op.drop_index(op.f('ix_allocation_account_id'), table_name='allocation')
    op.drop_table('allocation')
    op.drop_index(op.f('ix_template_account_id'), table_name='template')
    op.drop_table('template')
    op.drop_index(op.f('ix_key_date_subject_id'), table_name='key_date')
    op.drop_index(op.f('ix_key_date_kind_code'), table_name='key_date')
    op.drop_index('ix_key_date_due', table_name='key_date')
    op.drop_index(op.f('ix_key_date_account_id'), table_name='key_date')
    op.drop_table('key_date')
    op.drop_index(op.f('ix_contract_type_code'), table_name='contract')
    op.drop_index(op.f('ix_contract_status'), table_name='contract')
    op.drop_index(op.f('ix_contract_party_id'), table_name='contract')
    op.drop_index(op.f('ix_contract_number'), table_name='contract')
    op.drop_index(op.f('ix_contract_company_id'), table_name='contract')
    op.drop_index('ix_contract_account_status', table_name='contract')
    op.drop_index(op.f('ix_contract_account_id'), table_name='contract')
    op.drop_table('contract')
    op.drop_index(op.f('ix_asset_type_code'), table_name='asset')
    op.drop_index(op.f('ix_asset_parent_id'), table_name='asset')
    op.drop_index(op.f('ix_asset_company_id'), table_name='asset')
    op.drop_index(op.f('ix_asset_asset_type_id'), table_name='asset')
    op.drop_index(op.f('ix_asset_account_id'), table_name='asset')
    op.drop_table('asset')
    op.drop_index('ix_search_tsv', table_name='search_index', postgresql_using='gin')
    op.drop_index(op.f('ix_search_index_account_id'), table_name='search_index')
    op.drop_table('search_index')
    op.drop_index(op.f('ix_party_registry_code'), table_name='party')
    op.drop_index(op.f('ix_party_account_id'), table_name='party')
    op.drop_table('party')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_email_message_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_account_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_membership_user_id'), table_name='membership')
    op.drop_index(op.f('ix_membership_account_id'), table_name='membership')
    op.drop_table('membership')
    op.drop_index('ix_kdkind_code', table_name='key_date_kind')
    op.drop_table('key_date_kind')
    op.drop_index(op.f('ix_domain_event_ts'), table_name='domain_event')
    op.drop_index('ix_domain_event_entity', table_name='domain_event')
    op.drop_index(op.f('ix_domain_event_correlation_id'), table_name='domain_event')
    op.drop_index(op.f('ix_domain_event_account_id'), table_name='domain_event')
    op.drop_table('domain_event')
    op.drop_index(op.f('ix_company_account_id'), table_name='company')
    op.drop_table('company')
    op.drop_index(op.f('ix_auth_session_user_id'), table_name='auth_session')
    op.drop_table('auth_session')
    op.drop_index(op.f('ix_attachment_subject_type'), table_name='attachment')
    op.drop_index(op.f('ix_attachment_subject_id'), table_name='attachment')
    op.drop_index(op.f('ix_attachment_account_id'), table_name='attachment')
    op.drop_table('attachment')
    op.drop_table('user')
    op.drop_table('contract_type')
    op.drop_table('asset_type')
    op.drop_table('account')
    # ### end Alembic commands ###
